#quotation_admin:
#  path: quotation/admin/
#  methods: [GET, POST]
#  defaults:
#    _controller: 'Quotation\Controller\AdminQuotationController::quotationIndex'
#    _legacy_controller: 'AdminQuotationController'
#    _legacy_link: 'AdminQuotationController'

#quotation_admin_search_filters:
quotation_admin:
  path: quotation/admin/search/{name}/{reference}/{status}/{start}/{end}/{page}
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::quotationIndex'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
    name: null
    reference: null
    status: null
    start: null
    end: null
    page: 1
  requirements:
    page: '\d+'

quotation_admin_add:
  path: quotation/admin/add
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::add'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_search_customers:
  path: quotation/admin/search/customers/{query}
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::searchCustomers'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_customer:
  path: quotation/admin/show/customer/{id_customer}
  requirements:
    id_customer: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_show_customer_details:
  path: quotation/admin/show/customer/{id_customer}/details
  requirements:
    id_customer: '\d+'
  methods: [GET]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::showCustomerDetails'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_ajax:
  path: quotation/admin/{id_customer}/ajax
  requirements:
    id_customer: '\d+'
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCarts'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'

quotation_admin_autocompletion_ajax:
  path: quotation/admin/autocompletion/customer
  methods: [GET, POST]
  defaults:
    _controller: 'Quotation\Controller\AdminQuotationController::ajaxCustomer'
    _legacy_controller: 'AdminQuotationController'
    _legacy_link: 'AdminQuotationController'
